name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2.0.3
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.2.0

    - name: Install ninja
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/ninja-bin; cd ${GITHUB_WORKSPACE}/ninja-bin
        wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
        unzip ninja-linux.zip
        rm ninja-linux.zip
        echo "::add-path::${GITHUB_WORKSPACE}/ninja-bin"

    - name: Run gofmt
      run: ./.travis.gofmt.sh

    - name: Test
      run: go test ./...
    
    - name: Test with race detector
      run: go test -race -short ./...
    
    - run: ./tests/test.sh
    - run: ./tests/test_tree_tests.sh
    - run: ./tests/test_tree_tests.sh -t
